In [1]:
# houshold features
#nbr households in municipality
#average age in municipality
#average household size municipality
import pandas as pd

In [2]:
#median/mean income for households in municipality

def mean_income_municipality(train_data, test_data):
    mean_rev = train_data[["municipality_name", "revenue"]].groupby(["municipality_name"]).mean().reset_index()
    mean_rev = mean_rev.rename(columns={'revenue':'mean_revenue_municipality'})

    train_data = train_data.merge(mean_rev, how="left", on=["municipality_name"])
    train_data = train_data.drop_duplicates(subset=['store_id'], keep='first')

    # merge to test data
    test_data = test_data.merge(mean_rev, how="left", on=["municipality_name"])
    # In case of duplicates, remove them.
    test_data = test_data.drop_duplicates(subset=['store_id'], keep='first')
    return train_data, test_data

def mean_income_municipality(train_data, test_data):
    mean_rev = train_data[["municipality_name", "revenue"]].groupby(["municipality_name"]).median().reset_index()
    mean_rev = mean_rev.rename(columns={'revenue':'median_revenue_municipality'})
    
    train_data = train_data.merge(mean_rev, how="left", on=["municipality_name"])
    train_data = train_data.drop_duplicates(subset=['store_id'], keep='first')

    # merge to test data
    test_data = test_data.merge(mean_rev, how="left", on=["municipality_name"])
    # In case of duplicates, remove them.
    test_data = test_data.drop_duplicates(subset=['store_id'], keep='first')
    return train_data, test_data

In [9]:

grunnkrets_age = pd.read_csv('data/grunnkrets_age_distribution.csv')
mun = pd.read_csv('data/grunnkrets_norway_stripped.csv')
gk = grunnkrets_age['grunnkrets_id']
df = pd.DataFrame()
df['sum'] = grunnkrets_age.drop(['grunnkrets_id', 'year'], axis=1).sum(axis=1)
df['grunnkrets_id'] = grunnkrets_age['grunnkrets_id']
df = df.drop_duplicates(subset=['grunnkrets_id'], keep='first')
train_data = pd.merge(train_data, grunnkrets_stripped[['grunnkrets_id', 'municipality_name']], on='grunnkrets_id', how='left')
train_data.municipality_name = train_data.municipality_name.fillna('No municipality')
df

        sum  grunnkrets_id
0      1075       16013117
2       508       11030206
3       880       16011203
4       645        3011601
5       838        3010308
...     ...            ...
22607    95        9380108
22609    77        9380111
22611    84        9400101
22614    76        9400104
22617   138        9400108

[11379 rows x 2 columns]